### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by tylerfehr** [DarkVexon/FishingCharacter#5] opened 2023-10-03 23:43 UTC
```
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - ojb_infomod2 (0.0.7)
 - Better_Animation (0.2.0)
 - bossedrelics (2.6.0)
 - coloredpowertips (2.3.0)
 - ojb_easel (0.0.3)
 - ojb_mapmarks (0.0.1)
 - OptimizeTheSpire (1.1.0)
 - ramsaver (0.2.1)
 - stslib (2.10.1)
 - permNeow (1)
 - AIAdditions (1.5.0)
 - AKDsMoreRelics (1.5.1)
 - HugYouRelics (1.2.10)
 - fishing (3.4.5)
 - EphemeralMod (1.0.6.1)

Mods in stacktrace:
 - fishing (3.4.5)
Cause:
java.lang.NullPointerException
	at theFishing.FishingMod$1.onLoad(FishingMod.java:303)
	at theFishing.FishingMod$1.onLoad(FishingMod.java:289)
	at basemod.abstracts.CustomSavable.onLoadRaw(CustomSavable.java:42)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.LoadPlayerSaves.Postfix(LoadPlayerSaves.java:108)
	at com.megacrit.cardcrawl.core.CardCrawlGame.loadPlayerSave(CardCrawlGame.java:1245)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:801)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:423)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```
---
Likely culprits, if not directly caused by adventurer, are the last 5 mods in the list.

**Comment by tylerfehr** [comment] 2023-10-03 23:48
Launching the game again and the exception wasn't thrown, so we may have difficulty reproducing

**Comment by DarkVexon** [comment] 2023-12-01 17:25
Thanks for the report; this issue was fixed in an update a while ago (sorry, I never check Issues on this, LOL - usually bug reports are through steam or discord) - was caused by having a non-Adventurer run in progress, then resuming with Adventurer mod installed. All fixed; thanks for the report & for playing!

**Closed as completed by DarkVexon** 2023-12-01 17:25 UTC
